//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipeSIL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarangSupplier
    {
        public int IDBarangSupplier { get; set; }
        public int IDSupplier { get; set; }
        public int IDBarang { get; set; }
    
        public virtual Barang Barang { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
