//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipeSIL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int IDStock { get; set; }
        public Nullable<int> IDBarang { get; set; }
        public string NamaBarang { get; set; }
        public string KategoriBarang { get; set; }
        public int JumlahDiSupermarket { get; set; }
        public int JumlahDiGudang { get; set; }
        public int Terjual { get; set; }
    
        public virtual Barang Barang { get; set; }
    }
}
